"""empty message

Revision ID: 2a3402aafdaf
Revises: 5e5569e0d3eb
Create Date: 2023-04-29 00:02:30.486322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a3402aafdaf'
down_revision = '5e5569e0d3eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_constraint('follows_follower_id_key', type_='unique')
        batch_op.drop_constraint('follows_user_id_key', type_='unique')

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('likes_post_id_key', type_='unique')
        batch_op.drop_constraint('likes_user_id_key', type_='unique')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('posts_user_id_key', type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_unique_constraint('posts_user_id_key', ['user_id'])

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_unique_constraint('likes_user_id_key', ['user_id'])
        batch_op.create_unique_constraint('likes_post_id_key', ['post_id'])

    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_unique_constraint('follows_user_id_key', ['user_id'])
        batch_op.create_unique_constraint('follows_follower_id_key', ['follower_id'])

    # ### end Alembic commands ###
